DROP TABLE [dbo].[COMITE_ETICA$]
DROP TABLE [dbo].[CONSENTIMIENTO_INFORMADO$]
DROP TABLE [dbo].[DISPOSITIVOS_BIOMEDICOS$]
DROP TABLE [dbo].[DOCUMENTOS$]
DROP TABLE [dbo].[ENMIENDAS$]
DROP TABLE [dbo].[FASES$]
DROP TABLE [dbo].[H_PROTOCOLOS$]
DROP TABLE [dbo].[INSTITUCIONES$]
DROP TABLE [dbo].[INVESTIGADORES$]
DROP TABLE [dbo].[MANUAL_INVESTIGADOR$]
DROP TABLE [dbo].[MEDICAMENTOS$]
DROP TABLE [dbo].[PACIENTES$]
DROP TABLE [dbo].[PROTOCOLOS$]
DROP TABLE [dbo].[SUMINISTROS_IMPORTADOS$]
DROP TABLE [dbo].[SUSPENDER_INVESTIGACION$]

TRUNCATE TABLE [dbo].[COMITE_ETICA$]
TRUNCATE TABLE [dbo].[CONSENTIMIENTO_INFORMADO$]
TRUNCATE TABLE [dbo].[DISPOSITIVOS_BIOMEDICOS$]
TRUNCATE TABLE [dbo].[DOCUMENTOS$]
TRUNCATE TABLE [dbo].[ENMIENDAS$]
TRUNCATE TABLE [dbo].[FASES$]
TRUNCATE TABLE [dbo].[H_PROTOCOLOS$]
TRUNCATE TABLE [dbo].[INSTITUCIONES$]
TRUNCATE TABLE [dbo].[INVESTIGADORES$]
TRUNCATE TABLE [dbo].[MANUAL_INVESTIGADOR$]
TRUNCATE TABLE [dbo].[MEDICAMENTOS$]
TRUNCATE TABLE [dbo].[PACIENTES$]
TRUNCATE TABLE [dbo].[PROTOCOLOS$]
TRUNCATE TABLE [dbo].[SUMINISTROS_IMPORTADOS$]
TRUNCATE TABLE [dbo].[SUSPENDER_INVESTIGACION$]

SELECT * FROM [dbo].[COMITE_ETICA$]
SELECT * FROM [dbo].[CONSENTIMIENTO_INFORMADO$]
SELECT * FROM [dbo].[DISPOSITIVOS_BIOMEDICOS$]
SELECT * FROM [dbo].[DOCUMENTOS$]
SELECT * FROM [dbo].[ENMIENDAS$]
SELECT * FROM [dbo].[FASES$]
SELECT * FROM [dbo].[H_PROTOCOLOS$]
SELECT * FROM [dbo].[INSTITUCIONES$]
SELECT * FROM [dbo].[INVESTIGADORES$]
SELECT * FROM [dbo].[MANUAL_INVESTIGADOR$]
SELECT * FROM [dbo].[MEDICAMENTOS$]
SELECT * FROM [dbo].[PACIENTES$]
SELECT * FROM [dbo].[PROTOCOLOS$]
SELECT * FROM [dbo].[SUMINISTROS_IMPORTADOS$]
SELECT * FROM [dbo].[SUSPENDER_INVESTIGACION$]

/*Create corresponds camps to know time of elements*/
ALTER TABLE [dbo].[DOCUMENTOS$] ADD TIEMPO_RESPUESTA_DOCUMENTOS INT NULL ;
ALTER TABLE [dbo].[PROTOCOLOS$] ADD TIEMPO_EJECUCION_PROTOCOLO INT NULL;


-- Creates the login AbolrousHazem with password '340$Uuxwp7Mcxo7Khy'.  
CREATE LOGIN Andres   
    WITH PASSWORD = 'Heinsohn12#';  
GO  

-- Creates a database user for the login created above.  
CREATE USER Andres FOR LOGIN Andres;  
GO


/*CREATE DATAWAREHOUSE TABLE*/
CREATE TABLE DATAWAREHOUSE(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TIEMPO_EJECUCION_PROTOCOLOS INT,
	RAZON_SOCIAL nvarchar(200),
	DEPARTAMENTO nvarchar(50),
	MUNICIPIO nvarchar(50),
	ESTADO nvarchar(50)
);

SELECT * FROM DATAWAREHOUSE ORDER BY DEPARTAMENTO
DROP TABLE DATAWAREHOUSE




/*Next code is using in ssis to load the data corresponse to days between presentation and response of documents*/
/*UPDATE [dbo].[DOCUMENTOS$]
SET [TIEMPO_RESPUESTA_DOCUMENTOS] = DATEDIFF(day, [FECHA_PRESENTACION], [FECHA_RESPUESTA]) FROM [dbo].[DOCUMENTOS$];*/

/*UPDATE [dbo].[PROTOCOLOS$]
SET [TIEMPO_EJECUCION_PROTOCOLO] = DATEDIFF(day, [FECHA_PROTOCOLO], [FECHA_PREVISTA_TERMINACION]) FROM [dbo].[DOCUMENTOS$];*/